name: Deploy to GitHub Pages

on:
    workflow_run:
        workflows: [ Publish to GitHub Packages ]
        types:
            - completed

run-name: ${{ github.event.workflow_run.head_branch }}

env:
    OWNER: ${{ github.event.workflow_run.owner.login }}
    REPOSITORY: ${{ github.event.workflow_run.head_repository.name }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Stop old container
                run: docker stop ${{ env.REPOSITORY }}

            -   name: Remove old container
                run: docker container prune

            -   name: Login to GitHub Packages
                run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin

            -   name: Pull Docker image
                run: docker pull ghcr.io/${{ env.OWNER }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY }}:latest

            -   name: Run Docker container
                run: docker run --name ${{ env.REPOSITORY }} -p 3080:3000 -d ghcr.io/${{ env.OWNER }}/${{ env.REPOSITORY }}/${{ env.REPOSITORY }}:latest
